version: '3'
dotenv: ['Taskhost.env', 'Taskbase.env']

tasks:
  default:
    desc: Dummy
    silent: true
    interactive: false
    preconditions:
      - sh: '[ -n "{{.SLUG}}" ]'
        msg: 'SLUG is required'
    cmds:
      - echo TODO

  gitea:sync:
    desc: Sync repo from Gitea to Github
    silent: true
    interactive: false
    vars:
      API_ENDPOINT: '{{.GITEA_BASEURL}}/api/v1/repos/{{.GITEA_USER}}/{{.GITEA_REPO}}/mirror-sync'
      V: '{{default "0" .V}}'
      # {{$body_map := dict "owner" .GITEA_USER "repo" .GITEA_REPO}}
      # -d {{$body_map | toJson | squote}} \
    cmds:
      - |
        curl {{eq .V "1" | ternary "-v" "-s"}} -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: token {{.GITEA_AUTH_TOKEN}}" \
          "{{.API_ENDPOINT}}" {{if eq .V "0"}}| jq{{end}}
