version: '3'
dotenv: ['Taskhost.env', 'Taskbase.env']

tasks:
  default:
    desc: Dummy
    silent: true
    interactive: false
    preconditions:
      - sh: '[ -n "{{.SLUG}}" ]'
        msg: 'SLUG is required'
    cmds:
      - echo TODO

  gitea:sync:
    desc: Sync repo from Gitea to Github
    silent: true
    interactive: false
    vars:
      API_ENDPOINT: '{{.GITEA_BASEURL}}/api/vi/repos/{{.GITEA_USER}}/{{.GITEA_REPO}}/mirror-sync'
      BODY_MAP: '{{dict "owner" .GITEA_USER "repo" .GITEA_REPO}}'
    cmds:
      - 'echo curl -X POST -H "Content-Type: application/json" -H "Authorization: token {{.GITEA_AUTH_TOKEN}}" -d {{.BODY_MAP | toJson}} {{.API_ENDPOINT}}'
